# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and deploy demos

on:
  push:
    # branches:
    #   - develop
  # Only pushes to the develop branch should trigger the build and deploy of demos
  # pull_request:
  #   branches:
  #     - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install workspace dependencies
        run: npm install
      - name: Bootstrap lerna workspace
        run: npm run bootstrap
      - name: Build packages in workspace
        run: npm run build
      - name: Where am I?
        run: ls
      - name: Upload demo build artifcats
        uses: actions/upload-artifact@v3
        with:
          name: demos
          path: ./packages/echarts-demo/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Remove old demos
        run: rm -rf ./demos
      - uses: actions/download-artifact@v3
        with:
          name: demos
          path: packages/echarts-demo/build/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: Update demo files from GitHub Actions # from source of commit $GITHUB_SHA
          # Optional branch to push to, defaults to the current branch
          branch: gh-pages
