name: Create Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Semantic Version Number (i.e., 5.5.0 or patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        default: patch

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: main
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Reset main branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Change version number
        id: version
        run: |
          echo -n "::set-output name=next_tag::"
          lerna version ${{ github.event.inputs.versionName }} --no-private
      - name: Create pull request into main
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/${{ steps.version.outputs.next_tag }}
          commit-message: 'chore: release ${{ steps.version.outputs.next_tag }}'
          base: main
          title: Release ${{ steps.version.outputs.next_tag }}
          labels: release
          reviewers: dvdanielamoitzi
          assignees: dvdanielamoitzi
          body: |
            Releasing ${{ steps.version.outputs.next_tag }}.
